#!/bin/bash
. ./sh/common.sh
# Grep for and checkout branch
function g {
    branch=$(sed 's/^[ *]*//' <<<$1);
    if [[ "$branch" =~ ^remotes/  ]]; then
        branch="--track ${branch%remotes/}";
    fi;
    git co $branch;
};

n=$(wc -l <<<$"$1");
if [[ "$1" =~ ^[[:space:]]*$ ]]; then
    echo No matches;
    return 1;
elif [ $n == 1 ]; then
    g $1;
else
    export -f g;
    run_with_choice g "$1";
fi;
