#!/bin/bash
. /home/nadove/personal/code/nadove-git-config/sh/common.sh
# Hard reset followed by force push followed by chained push
refs=$(git hr $1 | tac);
git rhpf $(head -1 <<<"$refs");
git rhp $(tail -n +2 <<<"$refs");
