#!/bin/bash
. /home/nadove/personal/code/nadove-git-config/sh/common.sh
# Amend a commit on the current develop-descended branch with staged changes
git car0 || return 1;
target=$(git rev8 $1);
ESC=$(python -c 'print(chr(0x1b))');
fixup=__FIXUP__;
git ds;
git cm "${fixup}";
vcmds=$(printf "/${fixup}\ndd/${target}\np0dwif ${ESC}:wq");
git rbidev <<<"${vcmds}" || git r @~;
