#!/bin/bash
. ./sh/common.sh
# Unify `reset --hard <rev>` and `checkout <rev> -- <path>`
if grep -qPe "^-- " <<<"$@"; then
    git co @ $@;
elif grep -qPe " -- " <<<"$@"; then
    git co $@;
else
    git r --hard $@;
fi;
