#!/bin/bash
. /home/nadove/personal/code/nadove-git-config/sh/common.sh
# Precondition check for car(i)
if git ds --exit-code >/dev/null; then
    >&2 echo No changes staged;
    return 1;
elif ! git dd --exit-code >/dev/null; then
    >&2 echo Cannot rebase: there are unstaged changes;
    return 1;
fi;
