#!/bin/bash
. /home/nadove/personal/code/nadove-git-config/sh/common.sh
# Grep for and show commit on current develop-descended branch
function g () { git dr $(c8 <<<"$1"); };
run_with_choice g "$(git ldev | grep "$1")";
