#!/bin/bash
. /home/nadove/personal/code/nadove-git-config/sh/common.sh
# Commit changes to fixup! a selected commit on the current develop-descended branch
commits=$(git ldev);
function g { git cfr $(word1 "$1"); };
run_with_choice g "$commits";
